### PR TITLE
Kristofer patch 1, fixes #202 #203

### LINKED ISSUE #202: Responsive issue with "Add to MetaMask"
The left column resizes when the screen resizes. It becomes too crowded with the "Add to Metamask" button and the text next to each other. 

Skärmavbild 2021-03-11 kl  13 38 10

### PR DESCRIPTION
**Pull request by kristoferlund**
Patches to fix #202 and #203. 

#202
Fixes the responsive issue with the "Add to metamask" button

From: 
Skärmavbild 2021-03-11 kl  13 38 10

To:
Skärmavbild 2021-03-11 kl  13 38 21

#203 
I created a new `React.useEffect` focusing only on `balances` and `address` to prevent the DAI amount from being reset when user enters amount in input field.

ps. Possibly should have done two PRs, on for each fix. But … I was to fast and know to little about git to split after commits have been made to the same branch.

### CODE REVIEW

**Review by MerlinEgalite — APPROVED** [review]
Good to merge

**Review by MerlinEgalite — CHANGES_REQUESTED** [review]
There are some merge conflicts to fix before merging as I reverted the last PR merged (which should not have been merged in fact). Can you fix the merge conflict? Then I'll approve your changes :)

**Comment by kristoferlund** [comment]
@MerlinEgalite sure, done.

**Review by MerlinEgalite — APPROVED** [review]

**Comment by kristoferlund** [comment]
There was another collision on `setShowApplyToScholarshipTooltip`. Removed that, should be good to go now.

**Comment by MerlinEgalite** [comment]
No problem! Did you make all your changes?

**Comment by kristoferlund** [comment]
@MerlinEgalite Yup.

**Pull request merged**
