### PR TITLE
WIP Feat/donation

### LINKED ISSUE #191: Even tho I have reached my max trust score, i should still be able to donate
But the app won't let me :-(

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Do not merge it please.
Fix #191 and #201

### CODE REVIEW

**Comment by kristoferlund** [comment]
The DAI amount in the contribute form is auto reset back to 450 periodically when the component re-renders. Haven't looked at yet if that behaviour is introduced with this PR or if it was there before. 

https://user-images.githubusercontent.com/9698363/111222408-15349900-85dc-11eb-8253-a12107b2ffdc.mov

**Comment by kristoferlund** [comment]
Perhaps DAI entered should be stored in global redux state to avoid being reset on re-renders?

**Comment by MerlinEgalite** [comment]
@kristoferlund how many DAI do you have in your wallet? it's red it seems you don't have enough DAI. If you haven't donate yet the minimum is 450 DAI.
When I have enough DAI I can't see this pattern..

**Comment by kristoferlund** [comment]
@MerlinEgalite It occurs on the currently live site as well. So it is not related to this PR. If you merge this PR, I'll add a fix to the DAI reset issue. 👍 👍 👍

https://user-images.githubusercontent.com/9698363/111320833-ac92fe00-8667-11eb-8afe-8f612fd025a4.mov

**Review by kristoferlund — APPROVED** [review]
✅  👀 🧘‍♂️ 👏

**Pull request merged**
